jaffle_shop:
  outputs:
    dev:
      dbname: dbt_db
      host: postgres
      pass: password
      port: 5432
      schema: dbt_db
      threads: 4
      type: postgres
      user: admin
  target: dev
